### ISSUE TITLE
Process Selected Rows not working with Apex 21.1

### ISSUE THREAD

**Issue by Tom1101** [foex-open-source/fos-interactive-grid-process-rows#1]
Browser: Chrome, Edge, Firefox
Plugin version: 20.2.0
Apex version: 21.1.0

Action **Process Selected Rows** is not working with this APEX version

Action **Process Filtered Rows** is working properly

**Comment by mnolan866** [comment]
As a temporary workaround please edit the plugin and add a COMMIT statement after line 332 in the plugin PLSQL i.e. after "apex_exec.close(l_context);"

This will be included in the FOS 21.1 release which will be released soon.

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0

**Comment by Mabktst** [comment]
Looks like this is broken again in 22.2. PL/SQL Code is called for each row not only the selected rows.
