### ISSUE TITLE
Process Only works on default view

### ISSUE THREAD

**Issue by aldocano29** [foex-open-source/fos-interactive-grid-process-rows#2]
Hello,

I am working with apex 19.2

It seems that when an IG has more than one view (filtered report) the plugin only processes the rows from the default/primary view.

Looking at the debug, the values of the selected rows are stored inside the json object for all the views, but the process doesn't seem to take them in consideration when the current view is not the default/primary view.

![Screen Shot 2021-08-19 at 8 46 11 AM](https://user-images.githubusercontent.com/20285968/130079643-701237ba-3db4-4974-8a05-60212ba596d4.png)

**Comment by foex-open-source** [comment]
Thanks for reporting this issue, we are currently investigating it.

**Comment by foex-open-source** [comment]
Fixed with 21.2
